# Generated by Django 5.2.7 on 2025-10-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='store-custo_last_na_9e6315_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store-customers',
        ),
    ]
