# Generated by Django 5.2.7 on 2025-10-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_store_custo_last_na_9e6315_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='store_custo_last_na_e6a359_idx',
            old_name='store-custo_last_na_9e6315_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_customers',
        ),
    ]
