# Generated by Django 5.2.7 on 2025-10-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_store_custo_last_na_9e6315_idx_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birth_rate',
            new_name='birth_date',
        ),
    ]
