# Generated by Django 5.2.7 on 2025-10-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_birth_rate_customer_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ibventory',
            new_name='inventory',
        ),
    ]
